### ISSUE TITLE
Question about labeled texts

### ISSUE THREAD

**Issue by FantasyJXF** [mantra-inc/open-mantra-dataset#3]
images/boureisougi/ja/006.jpg

![image](https://user-images.githubusercontent.com/16235526/105034859-142c3300-5a95-11eb-82e6-57d08dda129a.png)

images/balloon_dream/ja/000.jpg
![image](https://user-images.githubusercontent.com/16235526/105034955-3e7df080-5a95-11eb-80f5-9f7da7b54b3b.png)

Only vertical texts are labeled?

**Comment by rhina** [comment]
We currently only label typed texts that contains a character’s speech, monologue, or narration. It is not limited to vertical texts.
Some handwritten texts and the texts in pictures are not labeled.
