### ISSUE TITLE
Accessing PubManga Dataset

### ISSUE THREAD

**Issue by xyntechx** [mantra-inc/open-mantra-dataset#4]
Hello!

I am currently embarking on a research project on Document Layout Analysis, focusing on the analysis of manga. After reading your paper, I found that the **PubManga dataset** you have created would be very helpful for my project, specifically in terms of determining the reading order of speech bubbles. Having said that, I would be extremely grateful if you could provide me with **access to the PubManga dataset (with annotations, images, etc.)**.

Thank you so much!

**Comment by rhina** [comment]
sorry, PubManga dataset cannot be publicly available because of the copyright issue.

**Comment by xyntechx** [comment]
No worries! Thank you for the clarification 😄
