### ISSUE TITLE
Question about 512-pre defined class

### ISSUE THREAD

**Issue by gyupro** [mantra-inc/open-mantra-dataset#6]
Hi. I got interested in your work and appreciate for your excellent work.

In your paper, "Towards Fully Automated Manga Translation", you mentioned you pre-defined 512classes but I cannot find where list of this classes. Can you tell me what classes you defined in the paper?

Thanks in advance.

**Comment by Mindful** [comment]
@gyupro Thanks for your interest in Mantra's research/data! 
In the paper, 512 semantic tags are extracted using [illustration2vec](https://github.com/rezoo/illustration2vec), and used as input to the translation model (though this ultimately didn't improve performance). That data is not part of the dataset, as it was output from the above model as opposed to human annotation. 

Closing this issue for now as it's not really a problem with the data, but feel free to reach out with more questions.
